server:
  port: 8081
spring:
  application:
    name: CLIENT-ONE
  boot:
    admin:
      client:
        url: http://localhost:1111/
  management:
   endpoints:
      web:
        exposure:
          include:
            '*'

