spring:
  datasource:
    url: "jdbc:h2:./appdb"
    username: "nayana"
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true




